### ISSUE TITLE
Crates.io Availability / Library Usage

### ISSUE THREAD

**Issue by Holzhaus** [timrogers/litra-rs#16]
Is there a specific reason why the project is not available on crates.io? That would make it easy to install using `cargo install`.

It might also be useful to move everything except the CLI handling from `main.rs` into a separate `lib.rs` file, so that this can be used as a library.

Thanks for your effort!

**Comment by timrogers** [comment]
No reason! I'd welcome a PR to make it publishable on `crates.io` and to refactor the reusable code into `lib.rs` 😊

**Comment by Holzhaus** [comment]
The former is done here: https://github.com/timrogers/litra-rs/pull/17

Not sure if I find the time for the latter. I'll first check if I can somehow configure udev to automatically run `litra on` when the camera is accessed and `litra off` after the video call ends. :-)

**Comment by timrogers** [comment]
Fixed in #19 ✅

**Comment by Holzhaus** [comment]
FYI i just created an AUR package for it: https://aur.archlinux.org/packages/litra

**Comment by timrogers** [comment]
@Holzhaus Nice! What do you think of giving me admin rights? We can then integrate it into the CI/CD flow perhaps.

**Comment by Holzhaus** [comment]
The [Arch User Repository](https://wiki.archlinux.org/title/Arch_User_Repository) only contains package build scripts and users will always compile a package locally. Hence, building on CI is not possible in this case.

What we could do it automatically bump the package version when a tag is pushed. I could disown the package and give you ownership if you want.

**Comment by timrogers** [comment]
Ah, that makes sense! I'm happy to do that if you can give me access - my username is the same as my GitHub username.

**Comment by Holzhaus** [comment]
Not sure if you got a notification, but I added you as a contributor on the package.
