### ISSUE TITLE
Only one of my Litra lights is turning on

### ISSUE THREAD

**Issue by CypurrKitty** [timrogers/litra-rs#42]
I love the simplicity of this, but unfortunately it's only working on one of my lights. I have two currently.  Does this support more than one light?

**Comment by timrogers** [comment]
@CypurrKitty Sorry for missing your issue! 

Does this text from the readme help?:

> All of the these commands support a --serial-number/-s argument to specify the serial number of the device you want to target. If you only have one Litra device, you can omit this argument. If you have multiple devices, we recommend specifying it. If it isn't specified, the "first" device will be picked, but this isn't guaranteed to be stable between command runs.

If you have multiple devices, the commands will pick a random default by default.

You need to get a list of your devices with `litra devices`, and then use the `--serial-number` option with the other commands.

**Comment by CypurrKitty** [comment]
Thank you for the reply, I dunno how I missed that in the readme. Got everything working, thank you so much for making this!
