### ISSUE TITLE
[Feature Request] Increase/Decrease brightness/color temperature

### ISSUE THREAD

**Issue by soulchainer** [timrogers/litra-rs#47]
Great tool, thank you for your effort!

The only think I'm missing for it to be perfect are commands to increase/decrease the brightness/color temperature.

That way it would allow to use this with Stream Deck, Loupe Deck or just to add keybindings to increase/decrease the brightness/temp according to the light conditions (whose change along the time) 🙏.

**Comment by timrogers** [comment]
@soulchainer Thanks for reaching out! This is a nice idea! How would you feel about incrementing/decrementing by 10% each time?

**Comment by soulchainer** [comment]
@timrogers thanks for reply :). It would be pretty nice. In fact, some time ago I was using other software for this and I just had 10 extra buttons configured, each one to execute the cli command to set one static brightness value (no increment/decrement feature either), like a button for 10, another for 20, 30... Using an entire Stream deck page just for this. Having the incrementing/decrementing feature would prevent the need of doing that :3.
