### ISSUE TITLE
Apple Silicon Support

### ISSUE THREAD

**Issue by joshtbernstein** [timrogers/litra-rs#82]
Any plans for Apple Silicon support?

**Comment by timrogers** [comment]
I'm definitely open to it, but I need to buy an Apple Developer account! 💰 

I just run the AMD64 version on my Apple Silicon Mac with Rosetta - is there a reason you're not a fan of that approach?

**Comment by joshtbernstein** [comment]
I don't have anything that requires Rosetta and was trying to avoid installing it. If that's what you're recommending, I'll do that and you can close this.

**Comment by timrogers** [comment]
Thanks! That's good context. 

I think it's $79 - not a huge amount, but still quite a bit to pay for an open source project!

**Comment by joshtbernstein** [comment]
Happy to donate something towards that if it would help?

**Comment by timrogers** [comment]
Sure! You can send a contribution through GitHub Sponsors ✨ 

Let me make a deal with you: send me any amount and I'll get an ARM64 build released by the end of the week ❤️

**Comment by joshtbernstein** [comment]
Done. Let me know if you want me to do any testing or something. Appreciate you working on this!

**Comment by timrogers** [comment]
I've started working on this in a new PR, but I am blocked right now as Apple have told me I need to contact support to progress my Developer Program enrolment. 

I'll keep you updated!

**Comment by timrogers** [comment]
I got my Apple Developer account today, and I'm making progress on this in #85. 

Signing is working, but notarization is getting stuck, which is also required for the binary to run without extra clicks in System Settings. 

Judging from threads on the [Apple Developer forums](https://forums.developer.apple.com/forums/thread/756867), it is common for notarization to get stuck when you first set up your account, so I'm going to wait a few days.

**Comment by timrogers** [comment]
@joshtbernstein I think I've got it working in #85! Would you be able to try the compiled binary [here](https://github.com/timrogers/litra-rs/actions/runs/11132743315/artifacts/2002832662)? 

It has been compiled for `darwin-arm64`, and signed and notarized with my Apple Developer certificate, so you should be able to download and run it without Apple security stuff getting in the way. You will probably need to make it executable (`chmod +x`) after downloading.

Once you've tried it and we know it works, I'll merge the PR and cut a new release.

**Comment by joshtbernstein** [comment]
@timrogers Yep! That works. Just in time for a video call too!

**Comment by timrogers** [comment]
Hooray! 🥳 I'll get this shipped. Thanks for the quick response!

**Comment by timrogers** [comment]
Released in https://github.com/timrogers/litra-rs/releases/tag/v1.4.0 ✅
